// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvsrpkjysbucgtctfjpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2c3Jwa2p5c2J1Y2d0Y3RmanB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4ODE5MDAsImV4cCI6MjA1NzQ1NzkwMH0.R2vJ1tUNpmOmnaqL9mea2w_9yDUmNBWoskXw114XrAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);